name: respi
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  dio: ^5.9.0

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_login: ^6.0.0
  flutter_riverpod: ^3.0.3
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3
  dotted_border: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  custom_lint: ^0.8.0
  riverpod_lint: ^3.0.3

flutter:
  uses-material-design: true
  generate: true
  assets:
    - lib/assets/images/

flutter_icons:
  android: true
  ios: true
  image_path: "/assets/Respi_Image_1.png"
